### ISSUE TITLE
Question: is it possible to place an image in the background?

### ISSUE THREAD

**Issue by ericoporto** [hgupta9/ScintillaNET.Demo#8]
Thanks for such an awesome source code, lots of interesting usages are here! 

I have been looking a bit how one would be able to put an image in the background, say a pretty picture, or a pattern, or similar. I know it's possible to change the color, but is it possible to put such image?

**Comment by robinrodricks** [comment]
Ask upstream - https://github.com/jacobslusser/ScintillaNET/issues
